export const IMAGE_LIST_REQUEST = 'IMAGE_LIST_REQUEST';
export const IMAGE_LIST_SUCCESS = 'IMAGE_LIST_SUCCESS';
export const IMAGE_LIST_FAIL = 'IMAGE_LIST_FAIL';

export const ADD_TO_EDIT = 'ADD_TO_EDIT';
export const REMOVE_FROM_EDIT = 'REMOVE_FROM_EDIT';
export const CHANGE_EDIT_ITEM_POSTION = 'CHANGE_EDIT_ITEM_POSTION';
export const EDIT_ITEM_SORT = 'EDIT_ITEM_SORT';
export const UPDATE_SINGLE_LIST_ITEM = 'UPDATE_SINGLE_LIST_ITEM'

export const MAKE_EDITING_TRUE = 'MAKE_EDITING_TRUE';


export const SET_SINGLE_EDIT_ITEM = 'SET_SINGLE_EDIT_ITEM';
export const UPDATE_SINGLE_EDIT_ITEM = 'UPDATE_SINGLE_EDIT_ITEM';
export const REST_SINGLE_EDIT_ITEM = 'REST_SINGLE_EDIT_ITEM';